package Eleccion;


/**
* Eleccion/NodePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Eleccion.idl
* Wednesday, November 30, 2011 4:46:21 PM CST
*/

public abstract class NodePOA extends org.omg.PortableServer.Servant
 implements Eleccion.NodeOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("register", new java.lang.Integer (0));
    _methods.put ("removeNode", new java.lang.Integer (1));
    _methods.put ("message", new java.lang.Integer (2));
    _methods.put ("send", new java.lang.Integer (3));
    _methods.put ("election", new java.lang.Integer (4));
    _methods.put ("getLeader", new java.lang.Integer (5));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // Eleccion/Node/register
       {
         Eleccion.Node nodo = Eleccion.NodeHelper.read (in);
         this.register (nodo);
         out = $rh.createReply();
         break;
       }

       case 1:  // Eleccion/Node/removeNode
       {
         Eleccion.Node nodo = Eleccion.NodeHelper.read (in);
         this.removeNode (nodo);
         out = $rh.createReply();
         break;
       }

       case 2:  // Eleccion/Node/message
       {
         String msg = in.read_string ();
         this.message (msg);
         out = $rh.createReply();
         break;
       }

       case 3:  // Eleccion/Node/send
       {
         int v = in.read_long ();
         this.send (v);
         out = $rh.createReply();
         break;
       }

       case 4:  // Eleccion/Node/election
       {
         this.election ();
         out = $rh.createReply();
         break;
       }

       case 5:  // Eleccion/Node/getLeader
       {
         int $result = (int)0;
         $result = this.getLeader ();
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:Eleccion/Node:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Node _this() 
  {
    return NodeHelper.narrow(
    super._this_object());
  }

  public Node _this(org.omg.CORBA.ORB orb) 
  {
    return NodeHelper.narrow(
    super._this_object(orb));
  }


} // class NodePOA
