package Eleccion;


/**
* Eleccion/Node.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Eleccion.idl
* Wednesday, November 30, 2011 4:46:21 PM CST
*/

public interface Node extends NodeOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Node
