package Eleccion;


/**
* Eleccion/NodeOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Eleccion.idl
* Wednesday, November 30, 2011 4:46:21 PM CST
*/

public interface NodeOperations 
{
  void register (Eleccion.Node nodo);
  void removeNode (Eleccion.Node nodo);
  void message (String msg);
  void send (int v);
  void election ();
  int getLeader ();
} // interface NodeOperations
